<?php
       

if ($stats['quest'] == 1 && $stats['qok'] == 0 && ($unit['farmer'] + $unit['tfarmer']) >= 10){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 4 && $stats['qok'] == 0 && $unit['worker'] >= 10){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 7 && $stats['qok'] == 0 && $unit['strelets'] >= 5 && $weapon['mosinnagant'] >= 5){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 8 && $stats['qok'] == 0 && $unit['pistoleti'] >= 5 && $weapon['dp27'] >= 5){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 10 && $stats['qok'] == 0 && ($unit['farmer'] + $unit['tfarmer']) >= 20){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 11 && $stats['qok'] == 0 && $unit['worker'] >= 20){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 12 && $stats['qok'] == 0 && $unit['strelets'] >= 10 && $weapon['mosinnagant'] >= 10){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 13 && $stats['qok'] == 0 && $unit['pistoleti'] >= 10 && $weapon['dp27'] >= 10){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 14 && $stats['qok'] == 0 && ($unit['farmer'] + $unit['tfarmer']) >= 40){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 15 && $stats['qok'] == 0 && $unit['worker'] >= 40){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 16 && $stats['qok'] == 0 && $unit['strelets'] >= 20 && $weapon['mosinnagant'] >= 20){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 17 && $stats['qok'] == 0 && $unit['pistoleti'] >= 20 && $weapon['dp27'] >= 20){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 19 && $stats['qok'] == 0 && ($unit['farmer'] + $unit['tfarmer']) >= 80){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 20 && $stats['qok'] == 0 && $unit['worker'] >= 80){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 21 && $stats['qok'] == 0 && $unit['strelets'] >= 40 && $weapon['mosinnagant'] >= 40){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 22 && $stats['qok'] == 0 && $unit['pistoleti'] >= 40 && $weapon['dp27'] >= 40){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 23 && $stats['qok'] == 0 && $stats['cannon'] >= 1){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 24 && $stats['qok'] == 0 && $stats['wall'] >= 1){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 25 && $stats['qok'] == 0 && ($unit['farmer'] + $unit['tfarmer']) >= 160){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 26 && $stats['qok'] == 0 && $unit['worker'] >= 160){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 27 && $stats['qok'] == 0 && $unit['strelets'] >= 80 && $weapon['mosinnagant'] >= 80){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 28 && $stats['qok'] == 0 && $unit['pistoleti'] >= 80 && $weapon['dp27'] >= 80){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 30 && $stats['qok'] == 0 && $unit['strelets'] >= 160 && $weapon['mosinnagant'] >= 160){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 31 && $stats['qok'] == 0 && $unit['pistoleti'] >= 160 && $weapon['dp27'] >= 160){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	if ($stats['quest'] == 32 && $stats['qok'] == 0 && $stats['floor'] >= 10){ $stats['qok'] = 1; $update_stats = mysqli_query($con,"UPDATE `stats` SET `qok`='".$stats['qok']."' WHERE `id`='".$_SESSION['uid']."'") or die(mysqli_error($con)); }
	
?>